apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: old-final-project
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: old-argocd-apps
    repoURL: 'https://github.com/gtorres777/test_final_project'
    targetRevision: prod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
