apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-react-node-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-react-node-app
    repoURL: 'https://github.com/gtorres777/test_final_project'
    targetRevision: dev
  project: default
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
